adds gcrypt to systemd-journeld
PelionIoT/meta-pelion-edge pull request #181
Opened 2020-10-27 19:37 UTC by x85446

2020-10-27 19:41 UTC, psppalash commented
Will test the build on raspberry Pi. We can merge the PR after that.

2020-10-27 21:06 UTC, cmonr requested changes
Typos.

2020-10-27 21:06 UTC, cmonr commented on recipes-core/systemd/systemd-conf%.bbappend
> +SUMMARY = "adds flags to journeld.conf in a simlar way to the metod used by systemd-conf found in the systemd bitbake reciepe"
```suggestion
SUMMARY = "adds flags to journeld.conf in a simmilar way to the method used by systemd-conf found in the systemd bitbake reciepe"
```

2020-10-27 21:06 UTC, cmonr commented on recipes-core/systemd/systemd_%.bbappend
> +SUMMARY = "adds gcrypt (libgcrypt) to systemd binary for forward secure sealing (ffs) journeld"
```suggestion
SUMMARY = "adds gcrypt (libgcrypt) to systemd binary for forward secure sealing (ffs) journald"
```

2020-10-28 23:13 UTC, ygoyal18 approved these changes

2020-10-28 23:13 UTC, psppalash commented
Verified. We can merge this PR now.

2020-10-28 23:13 UTC, psppalash approved these changes

2020-10-29 00:42 UTC, cmonr approved these changes

2020-10-29 00:42 UTC, merged