Update Go to 1.14.6
PelionIoT/meta-pelion-edge pull request #230
Opened 2021-01-26 06:31 UTC by AriParkkila

Update Go to 1.14.6 for https://github.com/golang/go/issues/39698

2021-01-26 06:45 UTC, cmonr commented
If we're updating the rev, any reason why we wouldn't go to the most recent patch?
https://github.com/golang/go/releases/tag/go1.14.14

Also, is there a specific issue that this up-rev is fixing? It seems a bit arbritrary without a description as to why it's needed.

2021-01-26 11:58 UTC, JanneKiiskila commented
@cmonr - if you think 1.14.14 is the way to go, please amend the PR.

2021-01-26 18:05 UTC, cmonr commented
@JanneKiiskila @AriParkkila 

> Also, is there a specific issue that this up-rev is fixing? It seems a bit arbritrary without a description as to why it's needed.

What I was trying to figure out was if there was a specifc need for this PR outside of "the current version is old". The PR description made it unclear why the change was needed.

2021-01-26 20:31 UTC, JanneKiiskila commented
Some bugs that point towards Go issues with concurrency and/or memory handling.

2021-01-27 04:47 UTC, cmonr commented
Thanks @JanneKiiskila. I was unaware of those.

2021-01-27 04:53 UTC, cmonr commented
@AriParkkila How did you calculate the changed SHA sum?

Was going to provide a change request to 1.14.14 since it doesn't seem like we have any reason not to if were going to accept this, but I wasn't able to locallty regenerate the SHAs.

2021-01-27 05:01 UTC, cmonr requested changes
Holding after looking over internal rationale for keeping Go at v1.14.4.

Will need to be resolved within Jira.

2021-01-28 06:47 UTC, AriParkkila commented
Closed. Golang is planned to be updated to more recent version.

@cmonr Yocto reports SHAs for you as build warning, of course if it can apply patches etc.

2021-01-28 06:47 UTC, closed without merging