Upgraded parsec-tool to 0.3.0
PelionIoT/meta-pelion-edge pull request #285
Opened 2021-04-12 22:11 UTC by ygoyal18

2021-04-13 06:54 UTC, esajaa submitted a review, later dismissed

2021-04-13 07:16 UTC, JanneKiiskila requested changes
This one leaves freely hanging on main, we need to use a tag or hash so that the builds remain repeatable.

2021-04-13 07:16 UTC, JanneKiiskila commented
Filename should also match the version being pulled in.

2021-06-08 05:24 UTC, ygoyal18 commented
@JanneKiiskila The file name includes the version which needs to be pulled in. The branch=main is mentioned and SRC_REV=0.3.0 will be populated from file name.

2021-06-08 15:52 UTC, ygoyal18 commented on recipes-misc/parsec-tool/parsec-tool_0.3.0.bb
> +SRC_URI = "git://github.com/parallaxsecond/parsec-tool;protocol=https;branch=main"
Ahh okay. I will add a tag.

2021-06-08 15:53 UTC, ygoyal18 commented on recipes-misc/parsec-tool/parsec-tool_0.3.0.bb
> +SRC_URI = "git://github.com/parallaxsecond/parsec-tool;protocol=https;branch=main"
```suggestion
SRC_URI = "git://github.com/parallaxsecond/parsec-tool;protocol=https;branch=main;tag=${PV}"
SRCREV = "${PV}"
```

2021-06-08 15:55 UTC, x85446 approved these changes
LGTM

2021-06-08 15:56 UTC, merged

2021-06-08 17:15 UTC, JanneKiiskila commented
Ah, yes, that PV variable thing is more clever.